package isamm.ingenieur.deuxieme.bdmm.bibliothequemultimédia.utilities;

public class KeyWords {
	// ConnectionClass.java
	public static String _DBName = "DBName";
	public static String _Host = "Host";
	public static String _Port = "Port";
	public static String _User = "User";
	public static String _Pass = "Pass";
	public static String _Driver = "Driver";
	public static String _D_S_ = "D.S.";
	public static String _Url = "Url";
	public static String _C_S_ = "C.S.";
	public static String _F_S_ = "F.S.";
	public static String _DriverType = "DriverType";
	public static String _Connection = "Connection";
	public static String _ConnectionType = "ConnectionType";
	public static String _DonePopulating = "DonePupulating";
	public static String _Success = "Success";
	public static String _None = "None";
	public static String _Properties = "Properties";
	public static String _Check = "Check";
	public static String _Initialisation = "Initialisation";
	public static String _Get = "Get";
	public static String _Closed = "Closed";
	public static String _DBConf = "DBConf.inf";
	public static String _Local = "Local";
	public static String _Remote = "Remote";
	public static String _Default_User = "ingIM2";
	public static String _Default_Pass = "ing2";
	public static String _Default_Host = "localhost";
	public static String _Default_Port = "1521";
	public static String _Default_DBName = "orcl";
	public static String _Default_DriverType = "thin";
	public static String _Default_Connection = _Local;
	public static String _Models_Fields_Sep = ",";
	public static String _Tables = "Tables";
	public static String _Count = "COUNT";
	public static String _Max = "MAX";
	public static String _Null = "null";
	public static String _ShowImage = "ShowImage";
	public static String _ShowVideo = "ShowVideo";
	public static String _Delete = "Delete";
	public static String _DeleteLink = "DeleteLink";
	public static String _Update = "Update";
	public static String _ShowLivres = "ShowLivres";
	public static String _ShowReservation = "ShowReservation";
	public static String _ShowEmprunt = "ShowEmprunt";
	public static String _ReserverLivre = "ReserverLivre";
	public static String _EmpruntLivre = "EmpruntLivre";
	public static String _AuteurLivres = "Livres";
	public static String _EtudiantLives = "Livres";
	public static String _LivreAuteur = "Auteurs";
	public static String _AddLivre = "AddLivre";
	public static String _AddAuteur = "AddAuteur";
	public static String _Link = "Link";
	public static String _Add = "Add";
	public static String _Filter = "Filter";
	// ConnectionClass.java
}
